# Generated by Django 4.0.6 on 2022-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='details',
            field=models.TextField(),
        ),
    ]
