# Generated by Django 4.0.6 on 2022-07-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todotask_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='date_time',
        ),
    ]
